### ISSUE TITLE
Docker image release including the newest changes

### ISSUE THREAD

**Issue by dannyyy** [mesosphere/traefik-forward-auth#13]
Hi,
I wanted to use your awesome work to authenticate against google. But google doesn't know the `groups` claim. I saw, that two days ago the pull request was accepted which allows to specify the scope by ourselves. But unfortunately there is no up-to-date docker release. The last official `1.0.7` is few more days old. And the one from two days `35860bba1f8d` doesn't include this change.

I would really appreciate if you can kick on a new docker build.

Kind regards,
Danny

**Comment by renanqts** [comment]
If pass, please, add the new groups PR.

**Comment by jr0d** [comment]
latest tag is now 2.0.1; this contains #15 and rbac support.
