### ISSUE TITLE
_forward_auth_claims doesn't respect domain cookie property

### ISSUE THREAD

**Issue by geiseri** [mesosphere/traefik-forward-auth#23]
It looks like the group's cookie is not respecting the domain so that it will not allow anything else to log in.
![image](https://user-images.githubusercontent.com/2265693/75818518-02e81400-5d67-11ea-8057-6524f2ca6aa0.png)
If I look at the server I see the logs below:
![image](https://user-images.githubusercontent.com/2265693/75819145-1778dc00-5d68-11ea-8509-98e8eae8a5fe.png)

`1161f0309308` is my idp, and `c069e53d0118` is the auth docker.  If you see the idp returns the groups correctly, and it looks like the cookie is properly populated.  The issue is that chrome filters the cookie since its not associated with my `whois` domain.  If I roll back to 1.0.4 (before the groups change) it works properly.

**Comment by jr0d** [comment]
We we're not explicitly setting the cookie domain (if one is set) on the session cookie. The linked issue should correct this behavior.
