### ISSUE TITLE
Safari: redirect to localhost instead of the correct URL

### ISSUE THREAD

**Issue by FuNK3Y** [mesosphere/traefik-forward-auth#3]
When using Safari, client get redirected to localhost instead of the target web site.

This is caused by the fact that the redirect URL is wrong, it is `https:///site/path` instead of `https://site/path`. For all other browser this is not a problem, but Safari expend this syntax as `https://localhost/site/path`

**Comment by jr0d** [comment]
sorry for letting this slip through the cracks! I'll backport this into the 2.0.1 image
