### ISSUE TITLE
Pass list of Scopes as env variable

### ISSUE THREAD

**Issue by r2ronoha** [mesosphere/traefik-forward-auth#59]
At the moment the `SCOPE` env variable is a single string.
Would it be possible to update it so we can pass multiple scopes that will be consumed as an array?

**Comment by ammmze** [comment]
I just tested this, but you can just use a space delimited string in the `SCOPE` env var (here is what i just set in mine `SCOPE: openid email profile groups audience:server:client_id:kubernetes`). Despite the resulting scope being different [here](https://github.com/mesosphere/traefik-forward-auth/blob/732b4805a596e920830dccf8b30b6ac8228f3138/internal/handlers/server.go#L286-L291), the scope that is passed to the openid provider is still the same. I'm sure that somewhere internally the array of scopes is just joined with a space delimiter, so in effect these are the same:

```js
['openid', 'email', 'profile', 'groups'].join(' ') // "openid email profile groups"
```

vs

```js
['openid email profile groups'].join(' ') // "openid email profile groups"
```
