### ISSUE TITLE
Exclusive Whitelist ?

### ISSUE THREAD

**Issue by sebbrandt87** [mesosphere/traefik-forward-auth#8]
https://github.com/mesosphere/traefik-forward-auth/blob/master/internal/auth.go#L73-L79

We should have this condition not to be exclusive but additional.

So just as an if condition both.

**Comment by jr0d** [comment]
@sebbrandt87 I've got this fixed in https://github.com/mesosphere/traefik-forward-auth/pull/12

**Comment by jr0d** [comment]
#12 is merged and this should now be resolved.
